### ISSUE TITLE
DB not being restored from backup

### ISSUE THREAD

**Issue by miller5984** [hex7c0/mongodb-restore#13]
Hi,

I am trying to use this module to restore a backup so I can run tests from a fresh database everytime they are run on my local machine. However, when I try to run the commands from protractor, it doesn't restore the database from my backup, or dump folder.

This is my code:

`var restoreDb = require('mongodb-restore');`

`describe('The database should be restored', function(){`
      `restoreDb({`
            `uri: 'mongodb://localhost:27017/e2etest',`
            `root: 'test/data/mock/mockData/dump/e2etest',`
            `drop: true`
      `})`
`});`

This is the only code in my spec file, and I have restored successfully using the mongorestore command, so if you can help me find out what's wrong I would really appreciate it! Thanks

Edit: I noticed your "logger" property, so I logged it out and I am getting this error:

2016-12-02T18:32:15.762Z - info: restore start
2016-12-02T18:32:15.894Z - info: [INFO-Server:9712] 1480703535894 server localhost:27017 fired event connect out with message [object Object]
2016-12-02T18:32:15.900Z - info: [INFO-Server:9712] 1480703535900 server localhost:27017 connected with ismaster [{"ismaster":true,"maxBsonObjectSize":16777216,"maxMessageSizeBytes":48000000,"maxWriteBatchSize":1000,"localTime":"2016-12-02T18:32:15.897Z","maxWireVersion":2,"minWireVersion":0,"ok":1}]
2016-12-02T18:32:15.901Z - info: db open
2016-12-02T18:32:15.901Z - info: drop database
2016-12-02T18:32:16.327Z - info: db close
2016-12-02T18:32:16.328Z - info: restore stop
2016-12-02T18:32:16.328Z - info:  MongoError: exception: assertion src\mongo\db\catalog\database.cpp:472
    at Function.MongoError.create (C:\Users\user\project\product\node_modules\mongodb-restore\node_modules\mongodb-core\lib\error.js:31:11)
    at C:\Users\user\project\product\node_modules\mongodb-restore\node_modules\mongodb-core\lib\connection\pool.js:483:72
    at authenticateStragglers (C:\Users\user\project\product\node_modules\mongodb-restore\node_modules\mongodb-core\lib\connection\pool.js:429:16)
    at null.messageHandler (C:\Users\user\project\product\node_modules\mongodb-restore\node_modules\mongodb-core\lib\connection\pool.js:463:5)
    at Socket.<anonymous> (C:\Users\user\project\product\node_modules\mongodb-restore\node_modules\mongodb-core\lib\connection\connection.js:309:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)

**Comment by hex7c0** [comment]
hi miller5984,
did you create a backup with `mongodb-backup` or with `mongodump`?

**Comment by miller5984** [comment]
I used mongodb-backup. I discovered the issue though, and it was that my database was corrupted. So I dropped the corrupted database and everything works perfectly now. I'll just have to remember that weird errors like this probably mean that there's something wrong with the database.

**Comment by hex7c0** [comment]
ok thanks.
will this issue impact other people?

**Comment by miller5984** [comment]
If a database is corrupted, yes it will cause problems for other people. If the database is not corrupted and working normally (can be repaired, etc), then I haven't encountered any issues with it. It might be good to put somewhere (if it isn't already) that a mongodump of a database will not work with this module. It has to be backed up with the mongodb-backup module. The only reason I say this is because I didn't see anywhere this was stated, so I initially was using a regular dump which wasn't working.

**Comment by mryellow** [comment]
> did you create a backup with mongodb-backup or with mongodump?

Oh so this isn't `mongorestore` in javascript but an entirely different data format?
