### ISSUE TITLE
Getting the error when we try to restore the same file multiple times with (dropCollection: Array)

### ISSUE THREAD

**Issue by pradeepchandra551** [hex7c0/mongodb-restore#20]
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at Gunzip.Writable.write (_stream_writable.js:291:5)
    at ReadStream.ondata (_stream_readable.js:663:20)
    at ReadStream.emit (events.js:182:13)
    at ReadStream.Readable.read (_stream_readable.js:483:10)
    at flow (_stream_readable.js:911:34)
    at resume_ (_stream_readable.js:893:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at Gunzip.Writable.write (_stream_writable.js:291:5)
    at ReadStream.ondata (_stream_readable.js:663:20)
    at ReadStream.emit (events.js:182:13)
    at ReadStream.Readable.read (_stream_readable.js:483:10)
    at flow (_stream_readable.js:911:34)
    at resume_ (_stream_readable.js:893:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

how to resolve this?

**Comment by pradeepchandra551** [comment]
there is issue..

**Comment by pradeepchandra551** [comment]
there is no issue..my apologies..
